export const DATA_INFO_PAGES = 'DATA_INFO_PAGES';
export const REQUESTS_CARTOONS_PAGE = 'REQUESTS_CARTOONS_PAGE';
export const LOAD_POSTS = 'LOAD_POSTS';
export const DRAWER_DATA = 'DRAWER_DATA';
export const DRAWER_CLEAR = 'DRAWER_CLEAR';